"""empty message

Revision ID: 835ad3f82666
Revises: 871ff3027b9d
Create Date: 2020-08-26 18:28:05.514714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '835ad3f82666'
down_revision = '871ff3027b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'mobile',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    op.alter_column('users', 'nick_name',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'nick_name',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'mobile',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    op.drop_table('posts')
    # ### end Alembic commands ###
